################################
#                              #
#       CONFIGURAZIONI         #
#           GENERALI           #
#                              #
################################

homeTeleportDelay: 3