################################
#                              #
#       CONFIGURAZIONI         #
#           GENERALI           #
#                              #
################################

homeTeleportDelay: 3

Ranks:
  - Membro
  - Anziano
  - Moderatore
  - Leader
