name: RageFactions
version: '1.0-beta2'
main: it.gaetanodev.ragefactions.RageFactions
api-version: '1.20'
depend:
  - Vault
  - PlaceholderAPI
commands:
  f:
    description: Comandi Fazioni
    usage: /f <arg>
    aliases:
      - faction
      - factions
  fadmin:
    description: Comandi Admin
    usage: /fadmin <arg>
    aliases:
      - factionadmin
      - factionsadmin
    permission: ragefactions.admin
