################################
#                              #
#       CONFIGURAZIONI         #
#           GENERALI           #
#                              #
################################

homeTeleportDelay: 3
factionMaxNameLegnght: 8
factionMaxTagLenght: 4
